version: '2'
services:
  franz:
    build: ./franz-app
    command: thin -R config.ru -p 3000 start
    volumes:
      - ./franz-app:/app
    ports:
      - "3000:3000"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    links:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181"
  kafka:
    image: jzakrzeski/wurstmeister-kafka-docker:0.10.1.1
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - KAFKA_BROKER_ID_GENERATION_ENABLE=true
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_NUM_PARTITIONS=10
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    links:
      - zookeeper
  kafkacat:
    image: ryane/kafkacat:latest
    entrypoint: kafkacat -b kafka.local
    links:
      - kafka:kafka.local
